name = "fangorn-access-worker"
main = "src/index.ts"
compatibility_date = "2025-07-18"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "my-first-bucket"

[vars]
SETTLEMENT_REGISTRY_ADDRESS = "0x0309df3ccb232023934b68c9ed068dec74be42cc"
ARBITRUM_SEPOLIA_RPC = "https://sepolia-rollup.arbitrum.io/rpc"
TIMESTAMP_WINDOW = "60"

[observability]
enabled = true
head_sampling_rate = 1