name = "fangorn-access-worker"
main = "src/index.ts"
compatibility_date = "2025-07-18"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "my-first-bucket"

[vars]
SETTLEMENT_REGISTRY_ADDRESS = "0x282915f5c6f6c9b15c131fa379916da47754fbef"
ARBITRUM_SEPOLIA_RPC = "https://sepolia-rollup.arbitrum.io/rpc"
TIMESTAMP_WINDOW = "60"

[observability]
enabled = true
head_sampling_rate = 1